version: '2'
services:
  parity:
    image: parity/parity:v2.3.0
    container_name: parity_signer
    user: root
    entrypoint: /home/parity/bin/parity
    restart: always
    command:
      --engine-signer [Authority address]
      --min-gas-price 20000000000
      --nat "extip:[External IP]"
      --config /home/parity/parity-config/config/parity.toml
      --password /home/parity/parity-config/config/pw.txt
      --min-gas-price 100000000000
      --whisper
      --no-secretstore
      --no-secretstore-http
    volumes:
      - evan-network-chain:/home/parity/.local/share/io.parity.ethereum/
      - ./parity-config:/home/parity/parity-config/config
      - ./core-config/core.json:/home/parity/core-config/core.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  monitor:
    image: buythewhale/ethstats_monitor
    container_name: ethstats_monitor
    restart: always
    volumes:
      - ./ethstats/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  evan-network-chain: