[parity]
chain = "/home/parity/core-config/core.json"
keys_path ="/home/parity/parity-config/config/keys"

[rpc]
interface = "all"
hosts = ["all"]

[websockets]
disable = true

[ui]
disable = true

[mining]
author = "0x0000000000000000000000000000000000000000"