[parity]
chain = "/parity/config/testcore.json"

[rpc]
interface = "all"
hosts = ["all"]

[websockets]
disable = true

[ui]
disable = true

[mining]
tx_gas_limit = "60000000"
gas_floor_target = "60000000"